#!/bin/sh

# ci_post_clone.sh
# This script runs after Xcode Cloud clones the repository.
# It creates Secrets.swift with the FAL_KEY from environment variables.

set -e

echo "Creating Secrets.swift from environment variable..."

SECRETS_PATH="$CI_PRIMARY_REPOSITORY_PATH/meta-stickers/Secrets.swift"

cat > "$SECRETS_PATH" << EOF
//
//  Secrets.swift
//  meta-stickers
//
//  Auto-generated by CI - DO NOT COMMIT
//

import Foundation

enum Secrets {
    static var falAPIKey: String {
        return "$FAL_KEY"
    }
}
EOF

echo "Secrets.swift created successfully at $SECRETS_PATH"
